eTicaret.WebUI/Controllers/SiparisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eTicaret.WebUI.App_Classes;
using eTicaret.WebUI.Models;

namespace eTicaret.WebUI.Controllers
{
    public class SiparisController : Controller
    {
        // GET: Siparis
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SiparisVer()
        {
            if (User.Identity.IsAuthenticated)
            {
                aspnet_Users uye = Context.Baglanti.aspnet_Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                aspnet_Membership uyes = Context.Baglanti.aspnet_Membership.FirstOrDefault(x => x.UserId == uye.UserId);
                Musteri m = Context.Baglanti.Musteris.FirstOrDefault(x => x.Id == uye.UserId);
                ViewBag.M = m;
                ViewBag.MAdres = Context.Baglanti.MusteriAdres.Where(x => x.MusteriID == m.Id).ToList();
                ViewBag.Sepet = (Sepet)HttpContext.Session["AktifSepet"];
                return View(uyes);
            }
            else
            {
                return RedirectToAction("GirisYap", "Kullanici");
            }

        }
        
        //public PartialViewResult AdresSiparis(int? adid)
        //{
        //    var Sepet = (Sepet)HttpContext.Session["AktifSepet"];
        //    Sepet.AdresID = (int)adid;
        //    return PartialView();
        //}

        public ActionResult OdemeYap()
        {
            return View((Sepet)HttpContext.Session["AktifSepet"]);
        }

        [HttpPost]
        public ActionResult OdemeYap(int? kartno)
        {
            aspnet_Users uye = Context.Baglanti.aspnet_Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            aspnet_Membership uyes = Context.Baglanti.aspnet_Membership.FirstOrDefault(x => x.UserId == uye.UserId);
            Musteri m = Context.Baglanti.Musteris.FirstOrDefault(x => x.Id == uye.UserId);
            var sepet = (Sepet)HttpContext.Session["AktifSepet"];
            Sati s = new Sati();
            s.MusteriID = m.Id;
            s.ToplamTutar = sepet.ToplamTutar;
            s.SepetteMi = false;
            s.SiparisDurumID = 1;
            s.SatisTarihi = DateTime.Now;
            s.MusteriAdresID = sepet.AdresID;
            Context.Baglanti.Satis.Add(s);
            Context.Baglanti.SaveChanges();
            foreach (var item in sepet.Urunler)
            {
                SiparisDetay sd = new SiparisDetay();
                sd.UrunID = item.Urun.Id;
                sd.Adet = item.Adet;
                sd.Fiyat = item.Urun.SatiFiyat;
                sd.İndirim = item.Indirim;
                sd.SatisID = s.Id;
                Context.Baglanti.SiparisDetays.Add(sd);
                Context.Baglanti.SaveChanges();
            }
            HttpContext.Session.Remove("AktifSepet");

            Sati sat =Context.Baglanti.Satis.OrderByDescending(t => t.SatisTarihi).FirstOrDefault(x => x.MusteriID == m.Id);
            Session.Add("siparisId", sat.Id);

            

            return RedirectToAction("SiparisOnay");
        }

        public ActionResult SiparisOnay()
        {
            ViewBag.spt = Session["siparisId"];
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult OnayBekleyenSiparisler()
        {

            List<Sati> satis = Context.Baglanti.Satis.ToList();
            List<SiparisDetay> sdetay = Context.Baglanti.SiparisDetays.ToList();
            List<Urun> urunu = Context.Baglanti.Uruns.ToList();
            List<Musteri> ms = Context.Baglanti.Musteris.ToList();
            var satlist = from e in satis
                          join d in sdetay on e.Id equals d.SatisID into table1
                          from d in table1.ToList()
                          join i in urunu on d.UrunID equals i.Id into table2
                          from i in table2.ToList()
                          join g in ms on e.MusteriID equals g.Id into table3
                          from g in table3.ToList()
                          select new ViewModel
                          {
                              satis = e,
                              sdetay = d,
                              urunu = i,
                              ms = g
                          };
            ViewBag.Sdurum = Context.Baglanti.SiparisDurums.ToList();
            ViewBag.Odurum = Context.Baglanti.OdemeDurums.ToList();
            return View(satlist.OrderByDescending(x => x.satis.SatisTarihi));
        }

        [HttpPost]
        public ActionResult OnayBekleyenSiparisler(int odid, int sdid, int satid)
        {
            Sati sati = Context.Baglanti.Satis.FirstOrDefault(x => x.Id == satid);
            sati.OdemeDurumID = odid;
            sati.SiparisDurumID = sdid;
            Context.Baglanti.SaveChanges();
            return RedirectToAction("OnayBekleyenSiparisler");
        }

        public ActionResult KargoyaVerilenSiparisler()
        {
            List<Sati> satis = Context.Baglanti.Satis.ToList();
            List<SiparisDetay> sdetay = Context.Baglanti.SiparisDetays.ToList();
            List<Urun> urunu = Context.Baglanti.Uruns.ToList();
            List<Musteri> ms = Context.Baglanti.Musteris.ToList();
            var satlist = from e in satis
                          join d in sdetay on e.Id equals d.SatisID into table1
                          from d in table1.ToList()
                          join i in urunu on d.UrunID equals i.Id into table2
                          from i in table2.ToList()
                          join g in ms on e.MusteriID equals g.Id into table3
                          from g in table3.ToList()
                          select new ViewModel
                          {
                              satis = e,
                              sdetay = d,
                              urunu = i,
                              ms = g
                          };
            ViewBag.Kargo = Context.Baglanti.Kargoes.ToList();
            ViewBag.Odurum = Context.Baglanti.OdemeDurums.ToList();
            return View(satlist.OrderByDescending(x => x.satis.SatisTarihi));
        }


        [HttpPost]
        public ActionResult KargoyaVerilenSiparisler(int kgid, int satid, int? kgTkp)
        {
            Sati sati = Context.Baglanti.Satis.FirstOrDefault(x => x.Id == satid);
            sati.KargoID = kgid;
            sati.KargoTakipNo = kgTkp;
            sati.SiparisDurumID = 4;
            Context.Baglanti.SaveChanges();
            return RedirectToAction("KargoyaVerilenSiparisler");
        }

        public ActionResult TamamlananSiparisler()
        {
            List<Sati> satis = Context.Baglanti.Satis.ToList();
            List<SiparisDetay> sdetay = Context.Baglanti.SiparisDetays.ToList();
            List<Urun> urunu = Context.Baglanti.Uruns.ToList();
            List<Musteri> ms = Context.Baglanti.Musteris.ToList();
            var satlist = from e in satis
                          join d in sdetay on e.Id equals d.SatisID into table1
                          from d in table1.ToList()
                          join i in urunu on d.UrunID equals i.Id into table2
                          from i in table2.ToList()
                          join g in ms on e.MusteriID equals g.Id into table3
                          from g in table3.ToList()
                          select new ViewModel
                          {
                              satis = e,
                              sdetay = d,
                              urunu = i,
                              ms = g
                          };
            ViewBag.Kargo = Context.Baglanti.Kargoes.ToList();
            ViewBag.Odurum = Context.Baglanti.OdemeDurums.ToList();
            return View(satlist.OrderByDescending(x => x.satis.SatisTarihi));
        }

    }
}

eTicaret.WebUI/Views/Siparis/KargoyaVerilenSiparisler.cshtml
@{
    ViewBag.Title = "KargoyaVerilenSiparisler";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using eTicaret.WebUI.App_Classes
@model IEnumerable<ViewModel>

<section id="container" class="">
    <section class="wrapper">
        <section class="panel">
            <header class="panel-heading">
                Kargoya Verilen Siparişler
            </header>
            <div class="panel-body">
                <div class="adv-table">
                    <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
                        <thead>
                            <tr>
                                <th>Tarih</th>
                                <th>Müşteri</th>
                                <th class="hidden-phone">Id</th>
                                <th class="hidden-phone">Tutar</th>
                                <th class="hidden-phone">Ödeme Durum</th>
                                <th class="hidden-phone">Kargo Seç</th>
                                <th class="hidden-phone">Kargo Takip No</th>
                                <th class="hidden"></th>
                                <th class="hidden-phone">Onay</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                int satid = 0;
                                foreach (var db in Model)
                                {
                                    if (satid != db.satis.Id && db.satis.SiparisDurumID == 3 && db.satis.KargoTakipNo == null && db.satis.KargoID ==null && db.satis.OdemeDurumID==1)
                                    {

                                        <tr class="gradeA">
                                            <td>@db.satis.SatisTarihi</td>
                                            <td>
                                                @db.ms.Adi @db.ms.Soyadi<br />
                                                @db.ms.Telefon -
                                                @db.ms.EMail
                                            </td>
                                            <td class="hidden-phone">@db.satis.Id</td>
                                            <td class="center hidden-phone">@db.satis.ToplamTutar.ToString("0.##") ₺</td>
                                            <td class="hidden">
                                                @foreach (var dbu in Model)
                                                {
                                                    if (db.satis.Id == dbu.sdetay.SatisID && dbu.urunu.Id == dbu.sdetay.UrunID && db.satis.MusteriID == dbu.ms.Id)
                                                    {
                                                        <p><b>Ürün Adı: @dbu.urunu.Adi <br />Fiyatı : @dbu.sdetay.Fiyat ₺</b></p>
                                                    }
                                                }
                                                <p>
                                                <p><b>Adres :@db.satis.MusteriAdre.Adres</b></p>
                                            </td>
                                            <form action="/Siparis/KargoyaVerilenSiparisler" method="post" enctype="multipart/form-data">
                                                <td class="hidden-phone">

                                                    <p><b>@db.satis.OdemeDurum.Adi</b></p>
                                                </td>
                                                <td class="hidden-phone">
                                                    @if (db.satis.KargoID != null)
                                                    {
                                                        <p><b>@db.satis.Kargo.SirketAdi</b></p>
                                                    }

                                                    <select class="form-control m-bot15" name="kgid" value="default" required>
                                                        <option value="" selected="selected">Kargo Seçiniz</option>
                                                        @foreach (var x in ViewBag.Kargo)
                                                        {
                                                            <option value="@x.Id">@x.SirketAdi</option>
                                                        }
                                                    </select>
                                                    <select name="satid" hidden="hidden">
                                                        <option value="@db.satis.Id"></option>
                                                    </select>
                                                </td>
                                                <td class="hidden-phone">
                                                    @if (db.satis.KargoTakipNo != null)
                                                    {
                                                        <p>@db.satis.Kargo.SirketAdi</p>
                                                    }

                                                    <input type="text" placeholder="" id="f-name" class="form-control" name="kgTkp">
                                                    @*<input type="text" class="form-control" id="f-name" name="ktkp" placeholder="Kargo Takip Numarası Giriniz" required />*@
                                                </td>
                                                <td class="hidden-phone">
                                                    <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i></button>
                                                </td>
                                            </form>
                                        </tr>
                                    }
                                    satid = db.satis.Id;
                                }

                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </section>
</section>

eTicaret.WebUI/Views/Siparis/OdemeYap.cshtml
@{
    ViewBag.Title = "Odeme Yap";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}
@model eTicaret.WebUI.App_Classes.Sepet

<script src="~/Content/Js/bootstrap.min.js"></script>
<script src="~/Content/Js/jquery-1.11.1.min.js"></script>

<script>
        $(".OdemeYap").click(function () {
            document.forms["formCC"].submit();
            alert("oki doki");
        });
    });
</script>

<link href="~/Content/Css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
<div class="content">
    <!------ Include the above in your HEAD tag ---------->
    <div class="container">
        <div class='row'>

            <div class="site-title"><div class="site-inside"><span>Ödeme Sayfası</span></div></div>
            <div class="col-md-8">
                <div class="order-title">Sipariş Detayı</div>
                <div class="row">
                    <div class="col-md-12">
                        <ul class="checkout-info">
                            <li class="checkout-info-1">Ürünler</li>
                            <li class="checkout-info-2">Toplam</li>
                        </ul>

                        <div class="checkout-info-box">
                            @if (Model != null)
                            {
                                foreach (var item in Model.Urunler)
                                {
                                    <ul class="checkout-product">
                                        <li class="checkout-product-1">@item.Urun.Adi</li>
                                        <li class="checkout-product-2">@item.Urun.SatiFiyat.ToString("0.##") ₺</li>
                                    </ul>
                                }
                                <!-- CART DETAILS -->
                                <ul class="checkout-product o-last">
                                    <li class="checkout-product-1">Ara Toplam</li>
                                    <li class="checkout-product-2">0 ₺</li>
                                </ul>
                                <ul class="checkout-product o-last">
                                    <li class="checkout-product-1">Kargo</li>
                                    <li class="checkout-product-2">0 ₺</li>
                                </ul>
                                <ul class="checkout-product last">
                                    <li class="checkout-product-1">Toplam Tutar</li>
                                    <li class="checkout-product-2">@Model.ToplamTutar.ToString("0.##") ₺</li>
                                </ul>
                            }
                            <!-- CART DETAILS -->
                        </div>

                    </div>
                </div>
            </div>
            <div class='col-md-4'>
                <div class="order-title"><b>Kredi Kartı Bilgileri</b></div>
                <script src="~/Content/Js/JavaScript.js" type='text/javascript'></script>
                <form accept-charset="UTF-8" action="/Siparis/OdemeYap" class="require-validation" name="formCC" data-cc-on-file="false" data-stripe-publishable-key="pk_bQQaTxnaZlzv4FnnuZ28LFHccVSaj" id="payment-form" method="post">
                    <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓" /><input name="_method" type="hidden" value="PUT" /><input name="authenticity_token" type="hidden" value="qLZ9cScer7ZxqulsUWazw4x3cSEzv899SP/7ThPCOV8=" /></div>
                    <div class='form-row'>
                        <div class='col-xs-12 form-group required'>
                            <label class='control-label'>Kart Üzerindeki İsim</label>
                            <input class='form-control' size='4' type='text'>
                        </div>
                    </div>
                    <div class='form-row'>
                        <div class='col-xs-12 form-group card required'>
                            <label class='control-label'>Kart Numarası</label>
                            <input autocomplete='off' class='form-control card-number' size='20' type='text'>
                        </div>
                    </div>
                    <div class='form-row'>
                        <div class='col-xs-4 form-group cvc required'>
                            <label class='control-label'>CVC Kodu</label>
                            <input autocomplete='off' class='form-control card-cvc' placeholder='örn. 311' size='4' type='text'>
                        </div>
                        <div class='col-xs-4 form-group expiration required'>
                            <label class='control-label'>Tarih</label>
                            <input class='form-control card-expiry-month' placeholder='AY' size='2' type='text'>
                        </div>
                        <div class='col-xs-4 form-group expiration required'>
                            <label class='control-label'> </label>
                            <input class='form-control card-expiry-year' placeholder='YIL' size='4' type='text'>
                        </div>
                    </div>
                    <div class='form-row'>
                        <div class='col-md-12'>
                            <div class='form-control total btn btn-info'>
                                <b>Kartınızdan çekilecek miktar:</b>
                                @if (Model != null)
                                {
                                    <span class='amount'>@Model.ToplamTutar.ToString("0.##") ₺</span>
                                }
                                <
                            </div>
                        </div>
                    </div>
                    <div class='form-row'>
                        <div class='col-md-12 form-group'>
                            <br /><br />
                            <button class='btn btn-success btn-group-justified btn-lg OdemeYap' type='submit'>Ödeme Yap »</button>
                        </div>
                    </div>
                    <div class='form-row'>
                        <div class='col-md-12 error form-group hide'>
                            <div class='alert-danger alert'>
                                Please correct the errors and try again.
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class='col-md-4'></div>
        </div>
    </div>
</div>

eTicaret.WebUI/Views/Siparis/SiparisOnay.cshtml
@{
    ViewBag.Title = "SiparisOnay";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}
<div class="container">
    <div class="col-md-8">
        <div class="btn-group pull-right">
                <p><b>Siparişiniz işleme alındı.</b></p>
                <br /><br />
                <input type="text" name="onay" class="btn btn-success btn-lg" value="Onay kodunuz: #@ViewBag.spt" disabled</input>
                <br /><br />
        </div>
    </div>
</div>

eTicaret.WebUI/Views/Siparis/SiparisVer.cshtml
@{
    ViewBag.Title = "SiparisVer";
    Layout = "~/Views/Shared/SiteLayout.cshtml";
}
@model eTicaret.WebUI.Models.aspnet_Membership

<script src="~/Content/Zeon/js/jquery-1.10.0.min.js"></script>
<script>
    $(document).ready(function () {
        $("#aadres").change(function myfunction() {
            var kId = $(this).find("option:selected").attr("titleadr");//seçili option'u bul attribute'larından title'ı getir.
            $.ajax({
                type: "GET",
                url: "/Uye/AdresGetirWidget",
                data: { id: kId },
                success: function myfunction(veri) {
                    $(".adr").html('');
                    $(".adr").html(veri);
                },
                error: function myfunction() {
                    alert("Lütfen bir adres seçiniz...");
                }
            });
        });

        $(".SiparisVer").click(function () {

            document.forms["form1"].submit();
            document.forms["form2"].submit();
            //document.forms["form3"].submit();
        });

    });
    
        
    //    );
    //function checkforblank() {

    //    var location = document.getElementById('adres');
    //    var invalid = location.value == "Please Select";

    //    if (invalid) {
    //        alert('Please enter first name');
    //        location.className = 'error';
    //    }
    //    else {
    //        location.className = '';
    //    }

    //    return !invalid;
    //}

</script>

<div class="content">
    <div class="container">
        <div class="site-title"><div class="site-inside"><span>Sipariş Sayfası</span></div></div>
        <div class="row">
            @if (User.Identity.IsAuthenticated == false)
            {
                <div class="col-md-6">
                    <div class="forms-separation">
                        <div class="login-form-box">
                            <form action="/Uye/GirisYap" class="login-form" name="form" method="post">
                                <h3>Giriş</h3>
                                <p>Giriş Yapmak için Email Adresinizi Giriniz</p>
                                <input type="text" name="Email" class="login-line">
                                <p>Parola</p>
                                <input type="password" name="Parola" class="login-line">
                                <input type="checkbox" name="Hatirla"> Beni Hatırla
                                <input type="submit" value="Giriş Yap" class="button-6">
                                <a href="/Uye/ParolamiUnuttum" class="lost-password">Parolamı unuttum</a>
                            </form>
                        </div>
                    </div>
                </div>
            }
            <div class="col-md-6">
                <form action="/Uye/HesapDuzenle" method="post" class="register-form" role="form" name="form1">
                    <div class="order-title">İletişim Bilgileri</div>
                    <div class="row">
                        <div class="col-md-6">
                            <input type="hidden" class="form-control" id="email" name="Id" value="@Model.UserId">
                            <input type="hidden" class="form-control" id="f-name" name="KullaniciAdi" value="@User.Identity.Name">
                            <p>Ad <span class="neccesary">*</span></p>
                            <input type="text" name="Adi" class="input-line" value="@ViewBag.M.Adi" required>
                        </div>
                        <div class="col-md-6">
                            <p>Soyad <span class="neccesary">*</span></p>
                            <input type="text" name="Soyadi" class="input-line" value="@ViewBag.M.Soyadi" required>
                        </div>
                        <div class="col-md-6">
                            <p>TC Kimlik No <span class="neccesary">*</span></p>
                            <input type="text" name="Tckn" class="input-line" maxlength="11" value="@ViewBag.M.Tckn" required>
                        </div>
                        <div class="col-md-6">
                            <p>E-Mail<span class="neccesary">*</span></p>
                            <input type="text" class="input-line" id="email" name="EMail" value="@Model.Email" required>
                        </div>

                    </div>
                    <p>Telefon <span class="neccesary">*</span></p>
                    <input type="tel" name="Telefon" class="input-line" maxlength="15" value="@ViewBag.M.Telefon" required>
                </form>
            </div>
            <div class="col-md-6">
                <div class="order-title">Adres Bilgileri</div>

                @if (ViewBag.MAdres.Count != 0)
                {

                    <p>Adres Seç <span class="neccesary">*</span></p>
                    <div class="col-lg-10">
                        <form action="#" id="myform" method="post" class="form-horizontal clientType" name="form3">
                            @*@{
                                    Html.RenderAction("AdresSiparis", "Siparis");
                                }*@
                            <select id="aadres" class="form-control m-bot15 " name="aadres" onchange="checkforblank()">
                                <option>Lütfen Adres Seçiniz!</option>
                                @foreach (var adres in ViewBag.MAdres)
                                {
                                    <option value="@adres.Id" titleadr="@adres.Id">@adres.Adi</option>
                                }
                            </select>
                        </form>
                    </div>
                    <div class="adr">
                        <text></text>
                    </div>
                    <div class="button-group right">
                        <br />
                        <a href="/Uye/AdresEkle" class="button-6">Yeni Adres Ekle</a>
                    </div>

                }
                else
                {
                    <form action="/Uye/AdresEkle" method="post" class="form-horizontal" name="form2" role="form">
                        <input type="hidden" class="form-control" name="MusteriID" id="f-name" value="@Model.UserId">
                        <p>Adres Adı <span class="neccesary">*</span></p>
                        <input type="text" name="Adi" class="input-line" required>
                        <p>Adres <span class="neccesary">*</span></p>
                        <textarea name="Adres" type="text" rows="10" cols="30" class="input-line" required></textarea>
                    </form>
                }

            </div>
            <div class="clear"></div>

            <div class="col-md-12">
                <div class="order-title">Sipariş Detayı</div>
                <div class="row">
                    <div class="col-md-9">
                        <ul class="checkout-info">
                            <li class="checkout-info-1">Ürünler</li>
                            <li class="checkout-info-2">Toplam</li>
                        </ul>

                        <div class="checkout-info-box">
                            @if (ViewBag.Sepet != null)
                            {
                                foreach (var item in ViewBag.Sepet.Urunler)
                                {
                                    <ul class="checkout-product">
                                        <li class="checkout-product-1">@item.Urun.Adi</li>
                                        <li class="checkout-product-2">@item.Urun.SatiFiyat.ToString("0.##") ₺</li>
                                    </ul>
                                }


                                <!-- CART DETAILS -->
                                <ul class="checkout-product o-last">
                                    <li class="checkout-product-1">Ara Toplam</li>
                                    <li class="checkout-product-2">0 ₺</li>
                                </ul>
                                <ul class="checkout-product o-last">
                                    <li class="checkout-product-1">Kargo</li>
                                    <li class="checkout-product-2">0 ₺</li>
                                </ul>
                                <ul class="checkout-product last">
                                    <li class="checkout-product-1">Toplam Tutar</li>
                                    <li class="checkout-product-2">@ViewBag.Sepet.ToplamTutar.ToString("0.##") ₺</li>
                                </ul>
                            }
                            <!-- CART DETAILS -->
                        </div>

                    </div>
                    <div class="col-md-3">
                        <ul class="payment-method">
                            <li><label><input type="radio" id="payment_method_bacs" class="input-radio" name="payment_method" value="bacs" checked="checked"> Kredikartı</label></li>
                            <li><label><input type="radio" id="payment_method_bacs" class="input-radio" name="payment_method" value="bacs"> EFT ya da Havale</label></li>
                            <li><label><input type="radio" id="payment_method_cheque" class="input-radio" name="payment_method" value="cheque"> Kapıda Ödeme</label></li>
                        </ul>
                        <button type="submit" class="btn btn-success btn-lg SiparisVer">Ödeme Sayfasına Git</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>